const $=x=>document.getElementById(x);
$("date").value=new Date().toISOString().slice(0,10);
const KEY="footballAI.predictions.v6";
function tab(x){$("predict").classList.toggle("hidden",x!=="predict");$("dashboard").classList.toggle("hidden",x!=="dashboard");if(x==="dashboard")dashboard()}
function pct(x){return Math.round(x*100)+"%"} function fact(n){let r=1;for(let i=2;i<=n;i++)r*=i;return r} function poi(k,l){return Math.exp(-l)*l**k/fact(k)}
function lastForm(list){let fs=list.filter(x=>["FT","AET","PEN"].includes(x.fixture?.status?.short));let out={w:0,d:0,l:0,gf:0,ga:0};for(const f of fs){let h=f.teams.home.id===f.teams?.home?.id;let isHome=f.teams.home.id===f.teams.home.id;let goalsH=f.goals.home??0,goalsA=f.goals.away??0;let teamIsHome=f.teams.home.id===f.teams.home.id;/* fixture list endpoint returns the queried team; home/away is enough for form */if(f.teams.home.winner===true)out.w++;else if(f.teams.away.winner===true)out.l++;else if(f.teams.home.winner===null&&f.teams.away.winner===null)out.d++;out.gf+=goalsH;out.ga+=goalsA}return out}
function model(d){
 let hs=d.homeStats?.[0]||{},as=d.awayStats?.[0]||{};
 let hg=+(hs.goals?.for?.average?.home||hs.goals?.for?.average?.total||1.35),ag=+(as.goals?.for?.average?.away||as.goals?.for?.average?.total||1.1);
 let hc=+(hs.goals?.against?.average?.home||hs.goals?.against?.average?.total||1),ac=+(as.goals?.against?.average?.away||as.goals?.against?.average?.total||1.2);
 let hi=d.homeInjuries?.length||0,ai=d.awayInjuries?.length||0;
 let hf=lastForm(d.homeLast),af=lastForm(d.awayLast);
 let homeForm=(hf.w-hf.l)*.025,awayForm=(af.w-af.l)*.025;
 let lh=Math.max(.15,(hg+ac)/2+.15+homeForm-Math.max(0,hi-ai)*.02),la=Math.max(.15,(ag+hc)/2+awayForm-Math.max(0,ai-hi)*.02);
 let H=0,D=0,A=0,O=0,B=0,bp=0,bh=0,ba=0;
 for(let h=0;h<9;h++)for(let a=0;a<9;a++){let p=poi(h,lh)*poi(a,la);if(h>a)H+=p;else if(h===a)D+=p;else A+=p;if(h+a>=3)O+=p;if(h&&a)B+=p;if(p>bp){bp=p;bh=h;ba=a}}
 let sum=H+D+A;H/=sum;D/=sum;A/=sum;
 return{H,D,A,O,B,lh,la,score:`${bh} - ${ba}`,winner:H>=D&&H>=A?"Home Win":D>=H&&D>=A?"Draw":"Away Win",conf:Math.max(H,D,A),hi,ai,hf,af}
}
async function load(){let date=$("date").value;$("matches").innerHTML='<div class="loading">Loading fixtures…</div>';try{let r=await fetch("/api/fixtures?date="+date),x=await r.json();if(!r.ok)throw Error(x.error);$("matches").innerHTML=x.length?x.map(f=>`<article class="match" onclick="openMatch(${f.fixture.id})"><div class="league">${f.league.country} • ${f.league.name}</div><div class="teams"><span class="team"><img src="${f.teams.home.logo}">${f.teams.home.name}</span><b>VS</b><span class="team">${f.teams.away.name}<img src="${f.teams.away.logo}"></span></div><div class="time">${new Date(f.fixture.date).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</div></article>`).join(""):'<div class="empty">No fixtures found.</div>'}catch(e){$("matches").innerHTML='<div class="loading">'+e.message+'</div>'}}
async function openMatch(id){$("detail").classList.remove("hidden");$("detail").innerHTML='<div class="loading">Collecting data and calculating your model…</div>';try{let r=await fetch("/api/match/"+id),d=await r.json();if(!r.ok)throw Error(d.error);let m=model(d),f=d.fixture,h=f.teams.home,a=f.teams.away;savePrediction({id,f,m,h:h.name,a:a.name,date:f.fixture.date});$("detail").innerHTML=`<div class="top"><div class="muted">${f.league.name} • ${f.league.country}</div><div class="teams"><span class="team"><img src="${h.logo}">${h.name}</span><b>VS</b><span class="team">${a.name}<img src="${a.logo}"></span></div><div class="muted">${new Date(f.fixture.date).toLocaleString()}</div></div><div class="confidence"><div class="muted">CUSTOM MODEL LEAN</div><b>${m.winner}</b><br>${pct(m.conf)} raw probability</div><div class="grid"><div class="metric"><small>HOME</small><strong>${pct(m.H)}</strong></div><div class="metric"><small>DRAW</small><strong>${pct(m.D)}</strong></div><div class="metric"><small>AWAY</small><strong>${pct(m.A)}</strong></div><div class="metric"><small>OVER 2.5</small><strong>${pct(m.O)}</strong></div><div class="metric"><small>BTTS</small><strong>${pct(m.B)}</strong></div><div class="metric"><small>EXPECTED SCORE</small><strong>${m.score}</strong></div></div><div class="cols"><div class="box"><h3>Expected goals</h3><div class="row"><span>${h.name}</span><b>${m.lh.toFixed(2)}</b></div><div class="row"><span>${a.name}</span><b>${m.la.toFixed(2)}</b></div></div><div class="box"><h3>Recent form input</h3><div class="row"><span>${h.name}</span><b>${m.hf.w}W ${m.hf.d}D ${m.hf.l}L</b></div><div class="row"><span>${a.name}</span><b>${m.af.w}W ${m.af.d}D ${m.af.l}L</b></div><div class="row"><span>Injury records</span><b>${m.hi} / ${m.ai}</b></div></div></div><div class="box"><h3>Model note</h3><p class="note">V6 weights current attack/defence averages, home advantage, recent result balance and injury-record counts, then converts expected goals into probabilities with a Poisson distribution. It is an experimental model and not a guarantee.</p></div>`}catch(e){$("detail").innerHTML='<div class="loading">'+e.message+'</div>'}}
function savePrediction(x){let a=JSON.parse(localStorage.getItem(KEY)||"[]");if(!a.some(y=>y.id===x.id)){a.unshift({id:x.id,h:x.h,a:x.a,date:x.date,pH:x.m.H,pD:x.m.D,pA:x.m.A,pO:x.m.O,pB:x.m.B,score:x.m.score,winner:x.m.winner});a=a.slice(0,100);localStorage.setItem(KEY,JSON.stringify(a))}}
function dashboard(){let a=JSON.parse(localStorage.getItem(KEY)||"[]");let n=a.length;if(!n){$("dash").innerHTML='<div class="empty">No predictions recorded yet. Analyze some matches first.</div>';return}let avg=a.reduce((s,x)=>s+Math.max(x.pH,x.pD,x.pA),0)/n,o=a.reduce((s,x)=>s+x.pO,0)/n;$("dash").innerHTML=`<div class="cards"><div class="card"><small>Predictions saved</small><b>${n}</b></div><div class="card"><small>Average confidence</small><b>${pct(avg)}</b></div><div class="card"><small>Average Over 2.5 probability</small><b>${pct(o)}</b></div></div><div class="box"><h3>Recent predictions</h3>${a.slice(0,15).map(x=>`<div class="row"><span>${x.h} vs ${x.a}</span><b>${x.winner} • ${pct(Math.max(x.pH,x.pD,x.pA))}</b></div>`).join("")}</div><p class="note">This dashboard records predictions locally on your device. V7 can add automatic result syncing so the site measures real hit rate, calibration and market performance.</p>`}
load();